### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by josharmenta** [openmusic-project/openmusic#18]
Where can I find these packages now?

This is from the 6.14 readme.

;------------------------------------
; If you want to load and use OM code in LispWorks, 
; check/download the source package from the repository: 
; https://forge.ircam.fr/p/OM/ 
; 
; ...or clone it using GIT:
; $ git clone git://git.forge.ircam.fr/OM.git
;------------------------------------

**Comment by karimhaddad** [comment]
Hi 

The best to do and to be up to date is to use this repo here:
https://github.com/openmusic-project/openmusic.git
