### ISSUE TITLE
Audio Mixer does not change levels

### ISSUE THREAD

**Issue by jccerrillo** [openmusic-project/openmusic#20]
Hello,
Had a problem with the Audio Mixer in 6.14, updated to 6.16 and the issue is not resolved.
Trying to change the sound output levels of tracks (as in the tutorial patch example 1) does not work.

The patch also mentions a "general Audio Mixer" in (Menu "Windows") but I only see a MIDI mixer in the Windows menu.

All best,

JC

**Comment by karimhaddad** [comment]
Hi, 

The audio-mix-console, is as you stated not in the windows menu, and should be in the classes->audio menu. I will see to it in the coming version. However i didn't test it if it still works. for the moment you can call it by ctrl+click(win/linux) or option+click (mac) in the patch anb by typing its name.

Best
K
