### ISSUE TITLE
sound-normalize returns error

### ISSUE THREAD

**Issue by jccerrillo** [openmusic-project/openmusic#21]
Hello,

sound-normalize returns the following error:

> Error while evaluating the box SOUND-NORMALIZE : (method sound-normalize (om-sound-data)) is called with unpaired keyword in (0).

I tried giving values to keyword arguments without success.

All best,

JC

**Comment by karimhaddad** [comment]
This is apparently a usage error and not a code issue. Please post this here along with your patching example in order to see exactly what is wrong:

https://discussion.forum.ircam.fr/c/openmusic
