### ISSUE TITLE
Can't read anything (Arch Linux)

### ISSUE THREAD

**Issue by ethanb037** [openmusic-project/openmusic#22]
Hello, new to using OpenMusic and can't wait to learn.
I'm currently running the latest Manjaro Linux.

As you can see from the pictures, I can't read anything. And the program won't let me resize windows like I usually should be able to.
Any help appreciated.

![Screenshot from 2020-12-16 12-46-08](https://user-images.githubusercontent.com/76130337/102404708-eab34f80-3f9c-11eb-855c-c8106e6623dc.png)
![Screenshot from 2020-12-16 12-46-32](https://user-images.githubusercontent.com/76130337/102404710-eb4be600-3f9c-11eb-953e-08ad07b8290f.png)

**Comment by karimhaddad** [comment]
Hi, 

Sorry about that. Can you send us your specs (wm uname , etc.) It seems it is some font problems garbling  all this,
Best
K

**Comment by ethanb037** [comment]
> Hi,
> 
> Sorry about that. Can you send us your specs (wm uname , etc.) It seems it is some font problems garbling all this,
> Best
> K

Hi! Thanks for reply. I'm a beginner Linux user so bear with me.
I'm not running a VM. Running Manjaro 5.9.11-3 (Gnome edition) on a 2015 MacBook Pro. Lmk how to get any other specs you need!

**Comment by karimhaddad** [comment]
Dear Ethan, 

No worry, i am installing right now the latest Manjaro (gnome) on my vm and test it. I am aware of some incompatibilities with the latest gnome. I recommend to you to use xfce instead of gnome. It is lighter. you can still install it on top of your install.
Will be back to  you.

Best
K

**Comment by karimhaddad** [comment]
Dear Ethan, 

Ok well the problem is, Manjaro being a Archlinux based distribution, there is no OM package for installing on these system for the time being. So:
1) How did you install it?
2) if you did starting from the .deb package, yo will meet serious problems (see:  https://forum.manjaro.org/t/how-to-install-deb/34452)
I recommend you install ubuntu distribution instead, specially if you are new to Linux.
I will se if i can package in the future for Archlinux based distributions.

BEst
K

**Comment by j-bresson** [comment]
OM is already available and maintained on the Arch User Repositories: https://aur.archlinux.org/packages/openmusic-bin/

**Comment by karimhaddad** [comment]
Thanx Jean, 
Funny, although i did a search on the Manjaro repository with no success. Who did the packaging ?
Best
K

**Comment by karimhaddad** [comment]
Well apparently there is no .au package there... 
we'll find a solution...
Thnx for the link.
Best

**Comment by ethanb037** [comment]
Hmm. What should I do? I'm willing to do anything to get it to work on this G. Manjaro- I tried Ubuntu and just couldn't get it to my liking. 
But yes, I installed it through that link that Jean posted.

Let me know any solution- hopefully simple.
Ethan

**Comment by karimhaddad** [comment]
dear Ethan, 

Sorry but i am not able to locate the package itself starting from Jean's link. Can you point me to the exact link ?

**Comment by ethanb037** [comment]
https://aur.archlinux.org/packages/openmusic-bin/
Here it is- the same link as Jean's. But you don't download it from here of course, you use terminal `sudo pacman -Sy openmusic-bin`,

**Comment by karimhaddad** [comment]
Yes of course but this is not there unfortunately:
![Screenshot_2020-12-17_02-43-03](https://user-images.githubusercontent.com/16069737/102427504-cba2d500-4011-11eb-909f-6cdff11c8fae.png)

However i managed to make it run on your same distrib:
![Screenshot_2020-12-17_02-14-00](https://user-images.githubusercontent.com/16069737/102427604-f725bf80-4011-11eb-9fed-fad2e17428f9.png)

Here is what you do: 
1) download instead this:
   https://github.com/openmusic-project/openmusic/releases/download/v6.17/OM_6.17.tar.bz2

2) extract it wherever you like (i put all extra binaries in a folder ~/bin/ (ie in my home/myself/bin
3) create a shell script (simple text file) and name it 'om617' and write the following:
```
#!/bin/sh

LD_LIBRARY_PATH='.' /home/karim/bin/OM_6.17/OM_6.17
```
[of course change the path that will suit you]

4) make this text file executable:
    chmod u+x om617

5) now you can launch OM by:
  a)
` cd to ~/bin`
`./om617`
b) better add the the bin folder to your path in your ,zshrc

Now if you have the same problem, this means that there is some problem with your installation distrib. I am runing the same distrib on a VM and it runs perfectly OR the .aur package is not very well packaged (but i doubt it.)

Hope this helps
Best
K

**Comment by ethanb037** [comment]
> Yes of course but this is not there unfortunately:
> ![Screenshot_2020-12-17_02-43-03](https://user-images.githubusercontent.com/16069737/102427504-cba2d500-4011-11eb-909f-6cdff11c8fae.png)
> 
> However i managed to make it run on your same distrib:
> ![Screenshot_2020-12-17_02-14-00](https://user-images.githubusercontent.com/16069737/102427604-f725bf80-4011-11eb-9fed-fad2e17428f9.png)
> 
> Here is what you do:
> 
> 1. download instead this:
>    https://github.com/openmusic-project/openmusic/releases/download/v6.17/OM_6.17.tar.bz2
> 2. extract it wherever you like (i put all extra binaries in a folder ~/bin/ (ie in my home/myself/bin
> 3. create a shell script (simple text file) and name it 'om617' and write the following:
> 
> ```
> #!/bin/sh
> 
> LD_LIBRARY_PATH='.' /home/karim/bin/OM_6.17/OM_6.17
> ```
> 
> [of course change the path that will suit you]
> 
> 1. make this text file executable:
>    chmod u+x om617
> 2. now you can launch OM by:
>    a)
>    ` cd to ~/bin`
>    `./om617`
>    b) better add the the bin folder to your path in your ,zshrc
> 
> Now if you have the same problem, this means that there is some problem with your installation distrib. I am runing the same distrib on a VM and it runs perfectly OR the .aur package is not very well packaged (but i doubt it.)
> 
> Hope this helps
> Best
> K

Hi! Well, you did spell openmusic wrong :P 

I tried your directions and still did not work unfortunately... Will try to install again. Thanks a bunch.

**Comment by ethanb037** [comment]
I tried, and it did not work. 
Any other ideas to install? I tried making from CommonLisp to no avail- the operation kept failing. Any other place to install? I would try OM Sharp but there is no AUR yet.
Will try making from CommonLisp on Mac now, as it won't run from the package on Mac either currently due to OS Big Sur.

**Comment by ethanb037** [comment]
> Yes of course but this is not there unfortunately:
> ![Screenshot_2020-12-17_02-43-03](https://user-images.githubusercontent.com/16069737/102427504-cba2d500-4011-11eb-909f-6cdff11c8fae.png)
> 
> However i managed to make it run on your same distrib:
> ![Screenshot_2020-12-17_02-14-00](https://user-images.githubusercontent.com/16069737/102427604-f725bf80-4011-11eb-9fed-fad2e17428f9.png)
> 
> Here is what you do:
> 
> 1. download instead this:
>    https://github.com/openmusic-project/openmusic/releases/download/v6.17/OM_6.17.tar.bz2
> 2. extract it wherever you like (i put all extra binaries in a folder ~/bin/ (ie in my home/myself/bin
> 3. create a shell script (simple text file) and name it 'om617' and write the following:
> 
> ```
> #!/bin/sh
> 
> LD_LIBRARY_PATH='.' /home/karim/bin/OM_6.17/OM_6.17
> ```
> 
> [of course change the path that will suit you]
> 
> 1. make this text file executable:
>    chmod u+x om617
> 2. now you can launch OM by:
>    a)
>    ` cd to ~/bin`
>    `./om617`
>    b) better add the the bin folder to your path in your ,zshrc
> 
> Now if you have the same problem, this means that there is some problem with your installation distrib. I am runing the same distrib on a VM and it runs perfectly OR the .aur package is not very well packaged (but i doubt it.)
> 
> Hope this helps
> Best
> K

Do you think it could be an issue with fonts? Incorrect fonts? When I try to download a font in the source code it says I don't have an application that opens True Tone fonts.

**Comment by jnb-ableton** [comment]
@karimhaddad 
`>>> sudo pacman -Sy opnmusic-bin`
=> `openmusic-bin` !!

**Comment by karimhaddad** [comment]
it is most probable a problem with your installation regarding ttf fonts. Please do check out this issue. I have installed both versions (package aur and tgz binaries) and they all work out well on the same version of your distribution.

Best
K

**Comment by ethanb037** [comment]
> it is most probable a problem with your installation regarding ttf fonts. Please do check out this issue. I have installed both versions (package aur and tgz binaries) and they all work out well on the same version of your distribution.
> 
> Best
> K

It is not the font size, I have figured out- but the scaling factor. When I decrease my system scaling factor to 0.5 I can read it ok, but everything else is tiny so I can not keep it such.

Is there a way to decrease scaling factor just for one program?

**Comment by ethanb037** [comment]
Yup, it's a scaling issue. 
Run openmusic with run_scaled for Arch with the command `run_scaled --scale=2/1` which is 200% and it looks pretty good.

Any way to permanently change scaling factor for this one program? Maybe yours worked bc your display is different. If no ideas, I can mark this as resolved.

**Comment by karimhaddad** [comment]
Thanx Ethan, 

Yes i believe so. After all it is a Gnome related issue. I use OM on Debian on my laptop and extra screen. But i don't use Gnome. I use i3wm which i prefer the most as window manager.

Best
K

**Comment by ethanb037** [comment]
Thanks for the suggestion.
I switched from Gnome to XFCE and it works perfectly now. I think we should just say that OM is not compatible with Gnome....  
if it is in the future, would be very glad! For now, will have to cope with XFCE!

Ethan

**Comment by andersvi** [comment]
fwiw, openmusic for linux is developed on a gnome based distro (fedora).  I use gnome myself, and haven't seen any of the issues reported in this thread.  Sorry to be of little help.

Anders

**Comment by ethanb037** [comment]
> fwiw, openmusic for linux is developed on a gnome based distro (fedora). I use gnome myself, and haven't seen any of the issues reported in this thread. Sorry to be of little help.
> 
> Anders

The problem is with HiDPI due to my screen being a retina MacBook Pro- there is no ability to my knowledge for individual scaling for OM. Any fix for this? I would hate to have to run run_scaled everytime...

**Comment by karimhaddad** [comment]
Dear Ethan, 

I beleive all your problems come from the run_scaled script which is NOT in the ARCH, DEBIAN, FEDORA distributions but something exotic. So as stated by Anders, yes OM IS compatible with gnome. However it seems the scaling script doesn't apply to fonts ? (didn't test this). If you need scaled display i suggest you use xrandr or arandr to dcrease your resolution.

I will close therefore this issue which is not OpenMusic related. 

Best
K
