### ISSUE TITLE
OM 6.19 in OS Monterey

### ISSUE THREAD

**Issue by jinnandtonic** [openmusic-project/openmusic#28]
I updated to the new OS (oops) and now OM crashes upon opening.  Is there presently a workaround?

**Comment by karimhaddad** [comment]
Hi

Following a report on Lispworks mailing list, Lispworks is not yet ready for Macos Monterey (12) . Om relies om LW. So we must wait for an LW update.

By the way, it is always advised NOT to update an OS to its latest release BEFORE being sure that compatibility issues will not be raised.

Best
K
