### ISSUE TITLE
group-list expanded functionality

### ISSUE THREAD

**Issue by Nikoteemus** [openmusic-project/openmusic#37]
Hello,

I hope also suggestions are welcome here. I have a suggestion for an expanded version of group-list. I've been able to implement this via patches, but in seems to be highly inefficient as I personally need it for a test function.

Here is what my patch does:
-Groups lists normally, eg. (1 2 3 4 5 6) (1 2 3) -> ((1) (2 3) (4 5 6))
-Allows repetitions in grouping, signified here by a minus sign: eg.  (1 2 3 4 5 6) (1 2 -3)-> ((1)(2 3)(3 4 5))
-In the case the first number is negative, the repeated element is taken from behind the list: 
 (1 2 3 4 5 6) (-1 2 -3) -> ((6 1) (2 3) (3 4 5)).

Would someone here be able to implement a version that would be faster?
Thanks!

**Comment by karimhaddad** [comment]
Dear Nikoteemus, 

This thread is reserved only for bug reports. All other issues, such as request, code suggestions are welcome here:
https://discussion.forum.ircam.fr/c/openmusic/42
(You are required just to open a free account i n order to post). There are many user's subjects and issues reported here. I propose to you to post your request.
By the way your last example shouldn't be this instead?: ((6) (1 2) (2 3 4)) ?
Or maybe i didn't understand your grouping algorithm well ?
Best
K
