### ISSUE TITLE
Stopped working on Linux

### ISSUE THREAD

**Issue by kureta** [openmusic-project/openmusic#38]
When I launch openmusic from the desktop shortcut nothing happens. I tried launching it from the terminal, again nothing. Not even a console output, or any kind of message. It doesn't create any log files. It does not exit. Just hangs there forever. Only bit of information I could find was the `strace` output `futex(0x1220788, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1665310693, tv_nsec=514949000}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
`. I have no idea what this means but hopefully someone else does.

I tried it on Fedora, Fedora Silverblue, and Arch Linux. Same results in all of them.

**Comment by karimhaddad** [comment]
Hi, 

Please can you provide more information: 
which OpenMusic version are you running, 
are you running this from sources? 
which installers did you use?
Thank you
K

**Comment by kureta** [comment]
I used the latest rpm release from here (7.0) on Fedora, and `openmusic-bin` AUR package (currently at version 6.19-1) on Arch.

**Comment by karimhaddad** [comment]
Its is running well on fedora 32. Will check on Silverblue to see what's wrong.

**Comment by karimhaddad** [comment]
Can you test this rpm ?
[openmusic-7.1-1.x86_64.rpm.zip](https://github.com/openmusic-project/openmusic/files/9741755/openmusic-7.1-1.x86_64.rpm.zip)

**Comment by karimhaddad** [comment]
About silverblue:
Silverblue is not a 'normal' version of Fedora, it's an 'immutable' version,

So i am trying on workstation 36

**Comment by kureta** [comment]
Yeah sure. I was just setting up my new laptop. First tried Silverblue. I figured some things might not work since its 'special'. So I switched to Fedora Workstation 36. The same thing happened. Then I tried Arch, the same thing.

Now I am on Arch. I'll switch back to Fedora, try this new package and report back. By the way, it works on my Fedora Desktop without any problems. My laptop is a fresh install. Maybe that has something to do with it. Some dependencies that were not listed in the package were already installed due to other software.

**Comment by karimhaddad** [comment]
Dear Kureta, 

first of all thanks for reporting. I am installing right now a fresh Workstation 36 on my VM. Will try and also report back.

Best
K

**Comment by karimhaddad** [comment]
Dear Kureta, 

Yes you are right. Fedora 36 doesn't install by default some dependencies:
you will need:

portmidi and 
libcanberra-gtk2

This last one will install also gtk2 needed for OM's (lispworks) graphics. The reason that it will not run.
I will repackage this for fedora.

Best
K

**Comment by kureta** [comment]
gtk2 solves the issue. I guess you can close this. thanks again very much for your time. happy to have been of help.

**Comment by karimhaddad** [comment]
Yes it is gtk2 indeed. Thanx to your help i repackage it and soon will do a new release.

Best
K
