### ISSUE TITLE
Text navigation in object boxes

### ISSUE THREAD

**Issue by rubenphilipp** [openmusic-project/openmusic#39]
Hello,

though that is indeed a minor issue, I don't hesitate bringing it up as it might be a small workflow throttle for some… 
It seems as if the standard text navigation when entering information into object boxes seems to be buggy. On a Mac, Command-a works, but C-e doesn't cause the cursor to jump to the end of the line. I am pretty sure that this worked in the previous versions. 
Maybe someone familiar with the UI-code could have a look at this some time.

Installed version: 7.1 (Release 7.010000)
OS: MacOS 12.5.1

Thanks a lot and best regards!
Ruben

**Comment by karimhaddad** [comment]
Dear Ruben, 

Thank you for reporting this. However, can you be more specific about 'entering information into object boxes' ? Is it the info panels? or other interface? I can't locate it.

Best
K

**Comment by rubenphilipp** [comment]
Dear Karim,

thanks for having a look at this issue. Apologies for being unspecific about the boxes. I refer to the boxes within a patch (cf. attached screenshot).

<img width="383" alt="Bildschirmfoto 2022-10-19 um 23 34 09" src="https://user-images.githubusercontent.com/12574070/196809216-f58d63ed-f6b2-49dc-af30-73663ada01e9.png">


Hope this helps locating the issue.

Best regards
Ruben

**Comment by karimhaddad** [comment]
Dear Ruben, 

Ok now i get it. And yes this used to work prior to the auto-completion feature of the tty box, OR it could be a difference in LW7/LW8 issue. 

I will investigate, and will try to restore it without removing auto-completion which i think is really practical. 

Best
K

**Comment by rubenphilipp** [comment]
Marvelous! Auto-completion is indeed very handy.
Thanks a lot!

Best regards
Ruben
