### ISSUE TITLE
OMLempelText error: "Non-standard use of return inside FINALLY"

### ISSUE THREAD

**Issue by opasquetdotfr** [openmusic-project/openmusic#40]
Hello !

Using OMLempelText on OM 7.0 and 7.1 (Silicon), I am having an error with lztextgenerate:
Error while evaluating the box LZTEXTGENERATE : Non-standard use of return inside FINALLY

It runs like a charm with OM 6.20.

O.

**Comment by karimhaddad** [comment]
Dear O.

Updated the library in order to comply with LW8.
You will find it in the project's section here:

https://github.com/openmusic-project/OMLempelText/releases

Best regards
K

**Comment by opasquetdotfr** [comment]
Dear Karim !!

I hope you are doing well !

That is super great !
I will have a look asap and keep you informed.

Thanks for your time !

O.
