### ISSUE TITLE
CHORD-SEQ/NOTE/CHORD/POLY/VOICE error on Windows 11

### ISSUE THREAD

**Issue by Seilburg** [openmusic-project/openmusic#47]
Hello,

When attempting to open or use miniview on any 'score' object in OM7.2 on Windows 11 (22H2), I get the following error:

```An error of type simple-error occured: GetTextMetrics failed for HDC CB0113DF: version 16384, size 1707x960, font 1040845423 6, brush 9437200 2, pen 11534359 1.```

This prevents the object from opening.

Thanks,
Nigel

**Comment by karimhaddad** [comment]
Hi Nigel, 

Is it always the OM 7.2 release you are using here?

**Comment by Seilburg** [comment]
Hello Karim,

Unfortunately it is the case with all OM 7 releases, and OM 6.19 (I haven't tried other OM6 builds yet).

Nigel

**Comment by Seilburg** [comment]
That worked - thanks very much for your help with this!

**Comment by karimhaddad** [comment]
Great !
