### ISSUE TITLE
bug: voice: toggle first note -> rest -> note

### ISSUE THREAD

**Issue by andersvi** [openmusic-project/openmusic#48]
Hi Karim, others

in a voice: toggling the first object to a rest, and back to note breaks on calling 'inside on nil

Seems to relate to the recent commit ee994e0a

**Comment by andersvi** [comment]
One optiona is adding a default method for 'inside just returning its argument:

   (defmethod inside ((self t))  self)

afaict 'inside is used in the container and grap-container classes only?  Perhaps a default method for other objects returning its arg is good?

**Comment by karimhaddad** [comment]
THanx Anders, 

It's fixed now.
Best
K

**Comment by karimhaddad** [comment]
The fix is in the toggle method that i have fixed for a particular reason. Now making an inside method might break things, i don't know. Let us leave like that for the moment.
Thank you again for your contribution.

Best
K
