### ISSUE TITLE
mime-support not available in Ubuntu 24.04 (and possibly Debian 12)

### ISSUE THREAD

**Issue by bruggor10** [openmusic-project/openmusic#60]
Packe does not install on newer Ubuntu with apt due to a dependency issue (mime-support package has been split, see https://wiki.debian.org/mime-support)

please update the dependencies accordingly. For what I understand openmusic works also without mime-support.

**Comment by j5awry** [comment]
Came here to report the same. Debian unstable lacks `mime-support`, so the next release will have it dropped. Without going super deep into the code, i'm guessing `media-types` fulfills the `mime-support` as required by openmusic, but I'm not finding direct references. Likely handling auto-open capabilities, by reporting types it supports (assumption on my part).

**Comment by karimhaddad** [comment]
Thank you all for pointing me to this issue. 
I will correct it and it will be in our next release.
Meanwhile if you cannot install the package, my suggestion is to use the .tar.gz release that you will find along the releases. You can set it in any location (here it is in a ~/bin folder in the user's home). You just need to make an .sh file to call OM's image:

```
#!/bin/sh
LD_LIBRARY_PATH='.' /home/username/bin/OM_7.5/OM_7.5
```
where /home/username/bin/OM_7.5/  is the location of the untarred folder of OM

Best Regards
Karim
