### ISSUE TITLE
Inlet description popup

### ISSUE THREAD

**Issue by goncalogato** [openmusic-project/openmusic#61]
Hello,

When patching in OM, it would be very good to have the inlets popup their identification when making connections. Is this something that might be added in the future?

Thanks so much,
G

**Comment by karimhaddad** [comment]
Hi, 
Do you mean by that the popup tooltips?

Best
K

**Comment by goncalogato** [comment]
Yes, at the end of a new connection between objects. This would allow one to readily identify which inlet is right to connect.

**Comment by karimhaddad** [comment]
Ok g

This will be in the next release (in march).
Thank you for the suggestion.

Best
K
