### ISSUE TITLE
Microtonal playback

### ISSUE THREAD

**Issue by goncalogato** [openmusic-project/openmusic#62]
Hello,

It seems that the microtonal playback of score objects via MIDI is inconsistent. When I select score objects with 48 EDO, OM outputs MIDI correctly (1/8 to channel 2, 1/4 to channel 3, 3/8 to channel 4, as mentioned in SETTINGS). But when objects are set to 24 EDO approx, OM midi player wrongly outputs quarter-tones to channel 2 (even though in SETTINGS the first option is selected: 4, instead of 'depending on approx'). It essential to have the ability to control the output of microtones as they are output to a 4 channel system with the correct cent adjustments (0, +25, +50, +75) and freely choose to have any score object in either 24 or 48 EDO. Can this be checked out?

Also, CHORD and NOTE do not allow one to set the approx.

Thank you.

**Comment by karimhaddad** [comment]
Dear goncalo, 

No this is intentional. The parsing of 24 EDO is done differently such as it is parsed in couples:
1-3, 2-4, 5-7, 6-8, ... where the second channels (3,4,7,8...) are tuned 1/4 tone up. The reason is to allow more 24 EDO per port to be played if you need to have more than one pgm per port.

Of course the preference setting option is not taken into account. One should stick with 'depending on approx'.
This setting (parsing) is the legacy setting. However, if you think this should be otherwise, why not setting your ports to 48 EDO instead.

Best
K

**Comment by goncalogato** [comment]
Dear Karim,

Thank you for your message.

Here are the default settings:
<img width="360" alt="image" src="https://github.com/user-attachments/assets/d09801a4-18df-4f4a-9248-badd610c92ab" />

1st example:
<img width="620" alt="image" src="https://github.com/user-attachments/assets/293cc00e-6b77-4ca5-b760-b391d54e0087" />

CHORD showing the same behaviour. !/4 tones are output to channel 2 (which is configured to receive 1/8 tones as defined in Settings):
<img width="159" alt="image" src="https://github.com/user-attachments/assets/61139959-5955-456f-9f90-7ede106efed0" />

I hope this is clear.

Best

**Comment by goncalogato** [comment]
I guess when the setting 'Number of Channels' set to 4, OM is actually shifting according to approx. The allocation of quarter-tones to channel 3 should be fixed (and not revert to channel 2).

**Comment by karimhaddad** [comment]
Yes, 

Now I understand. It seems to be a bug. 
Will look into that.
And thank you for the feedback.
Notice, this doesn't happen when using fluidsynth. 

BEst
K

**Comment by karimhaddad** [comment]
Dear goncalo, 

I think its fixed now. It was a silly bug. 
You can find the fix patch here:
https://github.com/openmusic-project/openmusic/releases/download/v7.5/patch_171224.lisp

Please tell me if this works for you.
And thank you again for this feedback.

Best
K

**Comment by goncalogato** [comment]
It works. Thanks again. Best
