### ISSUE TITLE
pm2 CHORD-SEQ-ANALYSIS

### ISSUE THREAD

**Issue by goncalogato** [openmusic-project/openmusic#65]
pm2 CHORD-SEQ-ANALYSIS is having trouble outputting an SDIFFILE in my system. I recently installed the latest pm2 library and external (1.6.53). I had trouble authorizing the pm2.app because of an issue with the activation key file name: IRCAM supplied a Ircam_Authorization_Key.txt (that's Authorization, not Activation) but pm2 instructed to use "pm2 -init_key_file Ircam_Activation_Key.txt". I changed the command to "pm2 -init_key_file Ircam_Authorization_Key.txt" and used absolute paths for the files.

Back to OM, pm2 started to work. But, perhaps due to installing the patch_181224.lisp, CHORD-SEQ-ANALYSIS now generates and removes temp sdif files, and I think that is the reason why the SDIFFILE object can't get and hold them. I'm using CHORD-SEQ-ANALYSIS connected to SDIFFILE.

Thanks in advance
g

**Comment by karimhaddad** [comment]
Hi G,

Your first issue has nothing to do with OM. It is related to pm2 binary, which is a closed source project developed @ IRcam. Just to let you know.

The second issue, may result in an old patch tutorial. We have updated the om-pm2 library and this patch in particular to be compatible with the latest pm2 binary. Please maje sure you are using BOTH, the updated library and its tutorial help patch. You might be using an old tutorial patch. I am sorry about that, but this library is highly depended on the pm2 development branch.

Please G, let me know if it works for you.


BEst
K

**Comment by goncalogato** [comment]
Dear K,

I'm not using an old tutorial patch and I'm suing the latest libraries and pm2 binary. I'll move this to the pm2 repository.
