### ISSUE TITLE
TEXT-VIEW does not display data

### ISSUE THREAD

**Issue by goncalogato** [openmusic-project/openmusic#66]
Hello,

Although TEXT-VIEW is used to display a string, it can be used to visualize data. It does not accept values and will not accept a list like (8). It gives an error and subsequently inactivates OM. Can this be fixed? Even editing the default string "untitled" inactivates OM, so it might be very unstable.

Thank you
G

**Comment by karimhaddad** [comment]
Can you send me the error message ?

**Comment by karimhaddad** [comment]
Dear G, 

Yes you are again right. There was a trailing bug regarding this interfaces boxes and tooltips that generated an error.
I fixed this and will soon make available a new fix patch,
By the way, i just realized that i didn't include your proposition of tooltips/connection. Will include it in the next upcoming patch.

Thanx for all your precious reports.

BEst
K

**Comment by goncalogato** [comment]
Thanks again. G
